version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do contêiner para a porta 3000 do host
    environment:
      - PGUSER=postgres
      - PGPASSWORD=example
      - PGDATABASE=meubanco
      - PGHOST=db  # Nome do serviço PostgreSQL
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
